name: sds625_soccer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.20
  - pip:
      - h5py==3.12.1
      - loguru==0.7.2
      - numpy==2.0.2
      - pandas==2.2.3
      - pillow==11.0.0
      - plotly==5.24.1
      - prometheus-client==0.21.0
      - propcache==0.2.1
      - protobuf==5.28.3
      - pyarrow==18.0.0
      - pytest==8.3.3
      - scikit-learn==1.5.2
      - scipy==1.13.1
      - seaborn==0.13.2
      - streamlit==1.40.1
      - tensorflow==2.18.0
      - torch==2.5.1
      - torch-geometric==2.6.1
      - tqdm==4.67.0
